# Generated by Django 5.0.4 on 2024-04-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('user_id', models.CharField(default=True, max_length=60, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('user_username', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('user_password', models.CharField(blank=True, default=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'User_tb',
            },
        ),
    ]
