# Generated by Django 5.0.4 on 2024-05-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_firstname',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_lastname',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_middlename',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
