# Generated by Django 5.0.4 on 2024-05-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccount', '0002_userdata_user_firstname_userdata_user_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountdataModel',
            fields=[
                ('account_id', models.CharField(default=True, max_length=60, primary_key=True, serialize=False)),
                ('account_name', models.CharField(blank=True, default=True, max_length=120, null=True)),
                ('account_email_id', models.EmailField(blank=True, default=True, max_length=120, null=True)),
                ('account_phone_number', models.CharField(blank=True, default=True, max_length=120, null=True)),
                ('account_address_line_1', models.CharField(blank=True, default=True, max_length=120, null=True)),
                ('account_address_line_2', models.CharField(blank=True, default=True, max_length=120, null=True)),
                ('account_city', models.CharField(blank=True, default=True, max_length=120, null=True)),
                ('account_state', models.CharField(blank=True, default=True, max_length=120, null=True)),
                ('account_country', models.CharField(blank=True, default=True, max_length=120, null=True)),
                ('account_pincode', models.CharField(blank=True, default=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'account_data_tb',
            },
        ),
    ]
