# Generated by Django 5.0.4 on 2024-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccount', '0003_accountdatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdatamodel',
            name='account_address_line_1',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accountdatamodel',
            name='account_address_line_2',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accountdatamodel',
            name='account_city',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accountdatamodel',
            name='account_country',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accountdatamodel',
            name='account_email_id',
            field=models.EmailField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accountdatamodel',
            name='account_name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accountdatamodel',
            name='account_phone_number',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accountdatamodel',
            name='account_pincode',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accountdatamodel',
            name='account_state',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
