# Generated by Django 5.0.4 on 2024-05-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccount', '0004_alter_accountdatamodel_account_address_line_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('transaction_id', models.CharField(default=True, max_length=60, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('account_name', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('credit_amount', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('debit_amount', models.CharField(blank=True, default=None, max_length=120, null=True)),
            ],
            options={
                'db_table': 'transaction_detail_tb',
            },
        ),
    ]
