# Generated by Django 5.0.4 on 2024-06-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccount', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_gender',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
