# Generated by Django 5.0.4 on 2024-06-21 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccount', '0008_userdata_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdatamodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adminaccount.userdata'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adminaccount.userdata'),
        ),
    ]
