# Generated by Django 5.0.4 on 2024-06-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccount', '0009_accountdatamodel_user_transactionmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdatamodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminaccount.userdata'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminaccount.userdata'),
        ),
    ]
