# Generated by Django 5.0.4 on 2024-06-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccount', '0010_alter_accountdatamodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdatamodel',
            name='account_id',
            field=models.CharField(default=True, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_id',
            field=models.CharField(default=True, max_length=120, primary_key=True, serialize=False),
        ),
    ]
