# Generated by Django 5.0.4 on 2024-06-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccount', '0011_alter_accountdatamodel_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdatamodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_date',
            field=models.DateField(max_length=120),
        ),
    ]
