# Generated by Django 5.0.4 on 2024-06-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccount', '0012_remove_accountdatamodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
