# Generated by Django 5.0.4 on 2024-06-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccount', '0013_userdata_profile_image_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdatamodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='adminaccount.userdata'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='adminaccount.userdata'),
        ),
    ]
