# Generated by Django 5.0.4 on 2024-06-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccount', '0015_alter_accountdatamodel_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccountdataModel',
        ),
        migrations.DeleteModel(
            name='TransactionModel',
        ),
    ]
