# Generated by Django 5.0.4 on 2024-06-26 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccount', '0016_remove_transactionmodel_user_delete_accountdatamodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountdataModel',
            fields=[
                ('account_id', models.CharField(default=True, max_length=120, primary_key=True, serialize=False)),
                ('account_name', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('account_email_id', models.EmailField(blank=True, default=None, max_length=120, null=True)),
                ('account_phone_number', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('account_address_line_1', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('account_address_line_2', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('account_city', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('account_state', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('account_country', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('account_pincode', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='adminaccount.userdata')),
            ],
            options={
                'db_table': 'account_data_tb',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('transaction_id', models.CharField(default=True, max_length=120, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(max_length=120)),
                ('account_name', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('credit_amount', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('debit_amount', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='adminaccount.userdata')),
            ],
            options={
                'db_table': 'transaction_detail_tb',
            },
        ),
    ]
