# Generated by Django 5.0.4 on 2024-06-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminaccount', '0017_accountdatamodel_transactionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdatamodel',
            name='account_address_line_1',
        ),
        migrations.RemoveField(
            model_name='accountdatamodel',
            name='account_address_line_2',
        ),
        migrations.RemoveField(
            model_name='accountdatamodel',
            name='account_country',
        ),
    ]
